### PR TITLE
Docs: Add README and update the license

### PR DESCRIPTION
**Pull request by aerabi**

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
It would be good to include in the commit message changing the license a note that "this was approved by the author in a private e-mail to Théo Zimmermann". This would improve the traceability of the reasons of this change when people look at it in the future.

Additionally, FYI we usually transform the `description` file into a `meta.yml` file which allows generating some files, including the `README` using https://github.com/coq-community/templates. I think this could be done in a further PR (if you want, I can open it).

**Comment by aerabi** [comment]
> It would be good to include in the commit message changing the license a note that "this was approved by the author in a private e-mail to Théo Zimmermann". This would improve the traceability of the reasons of this change when people look at it in the future.

Squashed the two commits into one, and added the mentioned line to the commit message body. :+1: 
 
> Additionally, FYI we usually transform the `description` file into a `meta.yml` file which allows generating some files, including the `README` using https://github.com/coq-community/templates. I think this could be done in a further PR (if you want, I can open it).

That would be very nice, @Zimmi48. :pray:

**Comment by Zimmi48** [comment]
> That would be very nice

OK, I'll do this after you merge this PR.

Watch out that it seems that you use two different e-mail addresses for your commits and one of them is not known from GitHub. Cf. "@aerabi authored and Mohammad-Ali A'RÂBI committed 5 hours ago" in 273525ca2fca3fa96d743de56be12b4bfa26f088.

**Comment by aerabi** [comment]
Thanks for the tip, @Zimmi48. The general `git` configuration was wrong.

**Pull request merged**
